# Generated by Django 5.2.7 on 2025-10-19 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='share_percentage',
            field=models.FloatField(help_text='Percentage of total sales revenue (e.g., 12.5 for 12.5%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
