# Generated by Django 5.2.7 on 2025-10-19 03:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_worker_productionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_unit', models.IntegerField(help_text='How much the worker earns per unit of this product (UGX)', validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.worker')),
            ],
            options={
                'unique_together': {('worker', 'product')},
            },
        ),
    ]
