# Generated by Django 5.2.7 on 2026-04-26 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_quantity_alter_sale_recorded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerpayrate',
            name='rate_per_unit',
            field=models.IntegerField(help_text="How much the worker earns per unit of this product (SO'M)", validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
